{
 "title": "nmon_aix",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "SHOW TAG VALUES FROM CPU_ALL WITH KEY = \"host\""
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "SHOW MEASUREMENTS WITH MEASUREMENT =~ /CPU([0-9]+|_ALL)/"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage $hostname",
     "type": "timeseries",
     "description": "Показывает среднюю нагрузку на ядра: системой и пользователем.  ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$m: User% ($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/^$cpu$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "User%" }
       ]
      },
      {
       "alias": "$m: Sys% ($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/^$cpu$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Sys%" }
       ]
      },
      {
       "alias": "$m: Wait% ($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/^$cpu$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Wait%" }
       ]
      }
     ]
    },
    {
     "title": "Async processes ",
     "type": "timeseries",
     "description": "Показывает статистику асинхронного ввода-вывода для фоновых процессов. Процессы, использующие синхронный ввод-вывод ждут выполнения операции для продолжения работы. Асинхронные операции не блокируют пользовательский вывод и работу приложения.  ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "alias": "$m: running (count)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "PROCAIO",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "aiorunning" }
       ]
      },
      {
       "alias": "$m: total_cpu%",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "PROCAIO",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "aiocpu" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage $hostname",
     "type": "timeseries",
     "description": "Показывает общее количество оперативной памяти, занятой в MB.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "alias": "free ($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "MEM",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Real free(MB)" }
       ]
      },
      {
       "alias": "total ($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "MEM",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Real total(MB)" }
       ]
      }
     ]
    },
    {
     "title": "Memory Swap $hostname",
     "type": "timeseries",
     "description": "выводит информацию о файлах подкачки.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "alias": "free ($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "MEM",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Virtual free(MB)" }
       ]
      },
      {
       "alias": "total ($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "MEM",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Virtual total(MB)" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Context switches $hostname",
     "type": "timeseries",
     "description": "Содержит информацию о внутренней статистике ядер.  \nprocess switch (или context switch), количество контекстных переключений в секунду. Контекстное переключение - это переключение ядер с одного процесса или потока на другой. По количеству переключений контекста (если оно слишком высокое), можно понять, что система делает что-то не так.  ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "context switches ($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "PROC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "pswitch" }
       ]
      },
      {
       "alias": "system calls ($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "PROC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "syscall" }
       ]
      }
     ]
    },
    {
     "title": "System calls $hostname",
     "type": "timeseries",
     "description": "Количество системных вызовов в секунду. Соответственно: `read` - количество вызовов чтения в секунду, `write` - вызовов записи, `exec` - вызовов выполнения (процессов или команд), `fork` - вызовов создания нового процесса, практически полностью дублирующего один из текущих.  ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "alias": "fork ($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "PROC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "fork" }
       ]
      },
      {
       "alias": "exec ($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "PROC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "exec" }
       ]
      },
      {
       "alias": "read ($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "PROC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "read" }
       ]
      },
      {
       "alias": "write ($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "PROC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "write" }
       ]
      }
     ]
    },
    {
     "title": "Run queue $hostname",
     "type": "timeseries",
     "description": "Cуммарное количество процессов в секунду, которые выполняются в данный момент, но относительно количества ядер. Тут максимальное значение соответствует количеству ядер, а концепция такая: если для 2 ядер значение 2.0 - то получается, что ядра полностью загружены процессами в данный момент, и следующему поступившему процессу придется ждать. А вот если значение < 2.0, то следующий процесс сможет выполняться тут же.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Runnable ($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "PROC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Runnable" }
       ]
      }
     ]
    },
    {
     "title": "IPC messages $hostname",
     "type": "timeseries",
     "description": "`msg` - количество IPC-сообщений (interprocess communication - IPC, межпроцессорного взаимодействия), отправленных за секунду.  \n`sem` - количество вызовов системных операций семафора в секунду. Семафор - это одна из разновидностей IPC, т.е. межпроцессорного взаимодействия. (семафор со счетчиком - доступ к определенному ресурсу возможен для ограниченного количества процессов, определяемых значением счетчика - пока они не освободят ресурс, другие ждут).  ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "alias": "semaphore ($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "PROC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "sem" }
       ]
      },
      {
       "alias": "messages ($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "PROC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "msg" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DISK",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "DISKWRITE $hostname",
     "type": "timeseries",
     "description": "Показывает скорость записи на диски в KB/s. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "DISKWRITE",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "DISKREAD $hostname",
     "type": "timeseries",
     "description": "Показывает скорость чтения с дисков в KB/s.  \n`dm-XX` - это device mapper, подсистема (модуль) ядра Linux, которая позволяет создавать виртуальные блочные устройства ( ВБУ). ВБУ - это вид файла в Linux/UNIX-системах, который обеспечивает доступ к реальному или виртуальному устройству (в виде файла). Блочные устройства (БУ) - это, например, жесткий диск, CD-ROM и т.д. Эти устройства пишет/читают информацию блоками. Фактически данные параметры описывают скорость записи в _какие-то_ реальные или виртуальные диски (нам интересно это может быть в виду расположения в этих дисках каких-то частей системы).  \n`sda-XX` - это первый из жестких дисков, подключенных через SCSI (Small Computer System Interface - набор стандартов для подключения физических устройств в компьютере, фактически железный порт и чип, который обрабатывает подключенное к нему устройство). XX - это разделы этого первого диска. Если будет подключен второй диск, то он будет иметь название sdb, третий - sdc, и т.д.  ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "DISKREAD",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk writes per transfer",
     "type": "timeseries",
     "description": "Среднее количество KB, записываемых на диски за одну операцию записи (запись блочная).  ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "KB / xfer" } },
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "DISKAVGWIO",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk reads per transfer",
     "type": "timeseries",
     "description": "Среднее количество KB, считываемых с дисков за одну операцию чтения (чтение блочное).  ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "KB / xfer" } },
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "DISKAVGRIO",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk write time per transfer",
     "type": "timeseries",
     "description": "Disk Read Service Time msec/xfer - Среднее время обслуживания чтения с дисков за одну операцию чтения.  ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms / xfer" } },
     "targets": [
      {
       "alias": "$tag_name ",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "DISKWRITESERV",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk read time per transfer",
     "type": "timeseries",
     "description": "Среднее время обслуживания чтения с дисков за одну операцию чтения.  ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms / xfer" } },
     "targets": [
      {
       "alias": "$tag_name ",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "DISKREADSERV",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Disks block sizes $hostname",
     "type": "timeseries",
     "description": "Показывает средний размер блоков, поступающих на диски в секунду в KB/s. Это значение вычисляется как (diskwrite + diskread) / кол-во передач _(для блочных устройств передача данных происходит блоками, таким образом и получается средний размер блока, зная количество передач и размер переданных/принятых данных)_.  ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "DISKBSIZE",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk transfers $hostname",
     "type": "timeseries",
     "description": "Показывает количество передач (transfers) с/на диски в секунду _(т.е. количество блоков, которое был прочитано/передано на диск)_.  ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "DISKXFER",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "DISKBUSY $hostname",
     "type": "timeseries",
     "description": "Средняя занятость дисков в процентах.  ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "DISKBUSY",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk wait queue time per transfer",
     "type": "timeseries",
     "description": "Среднее время, проведенное в очереди ожидания диска на одну операция, в миллисекундах. Если количество запросов на обслуживание превышает глубину очереди на диске, запросы перемещаются в очередь ожидания. Эта метрика показывает время, затрачиваемое запросами ввода-вывода в очереди ожидания.  ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ms / xfer" } },
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "DISKWAIT",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "NET $hostname",
     "type": "timeseries",
     "description": "Показывает объем данных чтения-записи в KB/s для интерфейсов.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "alias": "$tag_name ($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "NET",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "NETPACKET $hostname",
     "type": "timeseries",
     "description": "Показывает количество отправляемых/принимаемых пакетов в секунду для интерфейсов.  ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "alias": "$tag_name ($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "NETPACKET",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Filespaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "JFS Filespaces $hostname",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "alias": "$tag_name ($col)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "JFSFILE",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}